// Store all action creators here

//Auth
export const AUTH_SLIDE = 'AUTH_SLIDE';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CHANGE_AUTH_MODE = 'CHANGE_AUTH_MODE';

export const CREATE_GIG_LOADING = 'CREATE_GIG_LOADING';
export const CREATE_GIG_SUCCESS = 'CREATE_GIG_SUCCESS';
export const CREATE_GIG_FAIL = 'CREATE_GIG_FAIL';


export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';


export const FETCH_GIGS_LOADING = 'FETCH_GIGS_LOADING';
export const FETCH_GIGS_SUCCESS = 'FETCH_GIGS_SUCCESS';
export const FETCH_GIGS_FAIL = 'FETCH_GIGS_FAIL';
export const SET_BROWSE_PAGE = 'SET_BROWSE_PAGE';
export const RESET_GIGS = 'RESET_GIGS';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';

export const SORT_GAME = 'SORT_GAME';

export const FETCH_SINGLE_GIG_SUCCESS = 'FETCH_SINGLE_GIG_SUCCESS';



export const SEND_INBOX_MESSAGE_SUCCESS = 'SEND_INBOX_MESSAGE';
export const SEND_INBOX_MESSAGE_FAIL = 'SEND_INBOX_MESSAGE_FAIL';


export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIl = 'FETCH_PROFILE_FAIl';
export const FETCH_PROFILE_LOADING = 'FETCH_PROFILE_LOADING';

export const CHANGE_PROFILE_PIC_SUCCESS = 'CHANGE_PROFILE_PIC_SUCCESS';
export const CHANGE_PROFILE_BIO_SUCCESS = 'CHANGE_PROFILE_BIO_SUCCESS';



// LEAVE REVIEW

export const PUBLISH_REVIEW_SUCCESS = 'PUBLISH_REVIEW_SUCCESS';
export const PUBLISH_REVIEW_FAIL = 'PUBLISH_REVIEW_FAIL';
export const PUBLISH_REVIEW_LOADING = 'PUBLISH_REVIEW_LOADING';