// Store all action creators here

//Auth
export const AUTH_SLIDE = 'AUTH_SLIDE';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';



export const CREATE_GIG_LOADING = 'CREATE_GIG_LOADING';
export const CREATE_GIG_SUCCESS = 'CREATE_GIG_SUCCESS';
export const CREATE_GIG_FAIL = 'CREATE_GIG_FAIL';


export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';


export const FETCH_GIGS_LOADING = 'FETCH_GIGS_LOADING';
export const FETCH_GIGS_SUCCESS = 'FETCH_GIGS_SUCCESS';
export const FETCH_GIGS_FAIL = 'FETCH_GIGS_FAIL';

export const FETCH_SINGLE_GIG_SUCCESS = 'FETCH_SINGLE_GIG_SUCCESS';